<a href="https://colab.research.google.com/github/eraliabd/DataScience/blob/main/%2310_Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ma'lumotlar tahlili. (NumPy kutubxonasi)**

# **NumPy kutubxonasi bilan ishlash**

 NumPy kutubxonasini chaqirib olish.

In [1]:
import numpy as np

# Massivga yo'naltirilgan dasturlash

### Tartiblash (Sorting)

In [2]:
# data
arr = np.random.rand(4) # 4 ta taxminiy elementlardan tashkil topgan massiv
arr

array([0.63997578, 0.41364701, 0.89964514, 0.17570499])

`sort` metodi

In [4]:
# 1-usul
sorted_arr = np.sort(arr) # arr massivni tartiblangan ko'rinishini sorted_arr joylaydi
sorted_arr

array([0.17570499, 0.41364701, 0.63997578, 0.89964514])

In [6]:
# 2-usul
arr.sort()
arr

array([0.17570499, 0.41364701, 0.63997578, 0.89964514])

In [7]:
# teskari tartiblash
rev_arr = -np.sort(-arr)
rev_arr

array([0.89964514, 0.63997578, 0.41364701, 0.17570499])

In [10]:
# 2D array (massiv)
arr2d = np.random.randn(2, 4) # (2, 4) random massiv
arr2d

array([[-0.52158125,  0.54953608, -0.64945112,  0.95900577],
       [ 0.22669741,  1.17087124,  0.57546169,  1.28169763]])

In [13]:
# axis = 0 ---> Qator
row_srt = np.sort(arr2d, axis=0) # 2d array ning har bir qatori bo'yicha tartiblangan ko'rinishi
row_srt

array([[-0.52158125,  0.54953608, -0.64945112,  0.95900577],
       [ 0.22669741,  1.17087124,  0.57546169,  1.28169763]])

In [14]:
# axis = 1 ---> Ustun
col_srt = np.sort(arr2d, axis=1) # 2d array ning har bir ustuni bo'yicha tartiblangan ko'rinishi
col_srt

array([[-0.64945112, -0.52158125,  0.54953608,  0.95900577],
       [ 0.22669741,  0.57546169,  1.17087124,  1.28169763]])