<a href="https://colab.research.google.com/github/eraliabd/DataScience/blob/main/%2313_working_with_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ma'lumotlar tahlili. (NumPy kutubxonasi)**

# **NumPy kutubxonasi bilan ishlash**

 NumPy kutubxonasini chaqirib olish.

In [1]:
import numpy as np

# Fayllar bilash ishlash

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('data', arr) # array ni faylga saqlash (file_name, array)

In [5]:
arr_load = np.load('data.npy') # fayldagi arrayni o'qish
arr_load

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.savez('arrays', a=arr, b=arr1) # bir nechta arrayni faylga saqlash,
# a va b keyinchalik faylni o'qishni oson qilish uchun

In [8]:
arrays = np.load('arrays.npz') # faylni o'qish

In [9]:
arrays['a'] # fayldan arr ni o'qish

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arrays['b'] # fayldan arr1 ni o'qish

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.savez_compressed('array_comp.npz', a=arr, b=arr1) # bir nechta arrayni hajmini kichraytirib(siqib) saqlash

In [16]:
# Numpy massivlarni yuklab olish
data = np.load('arrays.npz')

# Yuklab olingan massivlarning nomlarini olish
nomlar = data.keys()

# Nomlarni ekranga chiqarish
for nom in nomlar:
    print(nom)

a
b
