<a href="https://colab.research.google.com/github/eraliabd/DataScience/blob/main/%234_Boolean_idexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ma'lumotlar tahlili. (NumPy kutubxonasi)**

# **NumPy kutubxonasi bilan ishlash**

 NumPy kutubxonasini chaqirib olish.

In [1]:
import numpy as np

**N-o'lchamli massiv (array)larga ishlov berish**

# **Boolean indekslash**



In [2]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [3]:
# data
data = np.random.randn(7, 4)
data

array([[ 0.85706478,  1.00899901,  0.8611106 , -0.55620143],
       [-0.17415296, -1.07748514,  1.6470606 ,  0.15853106],
       [ 0.81022672, -1.25525208,  1.22975009, -0.67877846],
       [ 0.8005441 ,  0.87584822,  0.12143217,  0.09481701],
       [-1.44562835, -1.07261439,  1.14637094,  0.3210454 ],
       [ 1.89597379, -0.55003678,  1.45228816, -0.17038429],
       [ 1.34869467, -0.88933265, -0.29275045,  1.61780311]])

In [4]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [5]:
data[names == 'Hasan'] # Hasanga tegishli barcha ma'lumotlarni ajratib olish

array([[ 0.85706478,  1.00899901,  0.8611106 , -0.55620143],
       [-1.44562835, -1.07261439,  1.14637094,  0.3210454 ]])

In [6]:
data[names == 'Elyor'] # Elyorga tegishli barcha ma'lumotlarni ajratib olish

array([[ 0.8005441 ,  0.87584822,  0.12143217,  0.09481701],
       [ 1.34869467, -0.88933265, -0.29275045,  1.61780311]])

In [11]:
data[names == 'Hasan', 2:] # Hasanga tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([[ 0.8611106 , -0.55620143],
       [ 1.14637094,  0.3210454 ]])

In [12]:
data[names != 'Hasan'] # (!=)Hasandan tashqari barcha insonlarning ma'lumotlarni ajratib olish

array([[-0.17415296, -1.07748514,  1.6470606 ,  0.15853106],
       [ 0.81022672, -1.25525208,  1.22975009, -0.67877846],
       [ 0.8005441 ,  0.87584822,  0.12143217,  0.09481701],
       [ 1.89597379, -0.55003678,  1.45228816, -0.17038429],
       [ 1.34869467, -0.88933265, -0.29275045,  1.61780311]])

In [13]:
data[~(names=='Hasan')] # yuqoridagi cell bilan bir xil natijani berar ekan

array([[-0.17415296, -1.07748514,  1.6470606 ,  0.15853106],
       [ 0.81022672, -1.25525208,  1.22975009, -0.67877846],
       [ 0.8005441 ,  0.87584822,  0.12143217,  0.09481701],
       [ 1.89597379, -0.55003678,  1.45228816, -0.17038429],
       [ 1.34869467, -0.88933265, -0.29275045,  1.61780311]])

In [14]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[ 0.85706478  1.00899901  0.8611106  -0.55620143]
 [-0.17415296 -1.07748514  1.6470606   0.15853106]
 [ 0.81022672 -1.25525208  1.22975009 -0.67877846]
 [ 0.8005441   0.87584822  0.12143217  0.09481701]
 [-1.44562835 -1.07261439  1.14637094  0.3210454 ]
 [ 1.89597379 -0.55003678  1.45228816 -0.17038429]
 [ 1.34869467 -0.88933265 -0.29275045  1.61780311]]


In [16]:
mask = (names == 'Hasan') | (names == 'Husan') # "|" - or(yoki)
mask

array([ True,  True, False, False,  True, False, False])

In [17]:
data[mask] # Hasan va Husanga tegishli ma'lumotlarni ajratib olish

array([[ 0.85706478,  1.00899901,  0.8611106 , -0.55620143],
       [-0.17415296, -1.07748514,  1.6470606 ,  0.15853106],
       [-1.44562835, -1.07261439,  1.14637094,  0.3210454 ]])

In [18]:
data

array([[ 0.85706478,  1.00899901,  0.8611106 , -0.55620143],
       [-0.17415296, -1.07748514,  1.6470606 ,  0.15853106],
       [ 0.81022672, -1.25525208,  1.22975009, -0.67877846],
       [ 0.8005441 ,  0.87584822,  0.12143217,  0.09481701],
       [-1.44562835, -1.07261439,  1.14637094,  0.3210454 ],
       [ 1.89597379, -0.55003678,  1.45228816, -0.17038429],
       [ 1.34869467, -0.88933265, -0.29275045,  1.61780311]])

In [19]:
data[data<0]

array([-0.55620143, -0.17415296, -1.07748514, -1.25525208, -0.67877846,
       -1.44562835, -1.07261439, -0.55003678, -0.17038429, -0.88933265,
       -0.29275045])

In [22]:
data[data<0] = 0
data

array([[0.85706478, 1.00899901, 0.8611106 , 0.        ],
       [0.        , 0.        , 1.6470606 , 0.15853106],
       [0.81022672, 0.        , 1.22975009, 0.        ],
       [0.8005441 , 0.87584822, 0.12143217, 0.09481701],
       [0.        , 0.        , 1.14637094, 0.3210454 ],
       [1.89597379, 0.        , 1.45228816, 0.        ],
       [1.34869467, 0.        , 0.        , 1.61780311]])

2-AMALIY VAZIFA

Masala(1): 2-o'lchamli massiv yaratish

Masala sharti : Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv yaratuvchi funksiyani davom ettiring.

Yordam : arangedan foydalanish ishni osonlashtiradi

In [33]:
# JAVOBNI SHU YERGA YOZING
def nd_array():
  """Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi),
  qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv """
  arr = np.arange(9).reshape(3, 3)
  return arr
nd_array()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Funksiyani tekshirish"""
arr = nd_array() # massiv
assert arr.size == 9, f"elementlar sonida xatolik mavjud"  # elementlar soni
assert type(arr) == np.ndarray, f"massiv aniqlanmadi" #numpy array
# elementwise test
test_arr = np.arange(9).reshape(3, 3)
assert arr.shape == (3, 3), f"noto'g'ri qator va ustunlardan foydalanilgan"
assert True in np.in1d(arr, test_arr), f"elementlararo xatolik mavjud"

# Masala(2): Indeks yordamida 2-o'lchamli massivlardan elementlarni kesib olish
Masala : Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasini davom ettiring.

Yordam : 6 va 7 turgan indekslarni aniqlab olib, shu indekslar yordamida kesib oling. Natija: array([6, 7]) ko'rinishida bo'lishi kerak.**bold text**

In [35]:
# JAVOBNI SHU YERGA YOZING
def sliced_array_2d():
    """Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan
     qismini kesib olish funksiyasi """
    arr = nd_array() # yuqoridagi funksiya yordamida array yaratib olish
    return arr[2, :2]
sliced_array_2d()

array([6, 7])

In [39]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Funksiyani tekshirish"""
sl_arr_2d = sliced_array_2d() # kesib olingan massiv
assert sl_arr_2d.size == 2, f"elementlar sonida xatolik mavjud"  # elementlar soni
assert type(sl_arr_2d) == np.ndarray, f"massiv aniqlanmadi" #numpy array
# elementwise test
test_arr = np.array([6, 7])
assert sl_arr_2d.shape == (2,), f"kesib olingan massiv shaklida xatolik mavjud"
assert True in np.in1d(sl_arr_2d, test_arr), f"elementlararo xatolik mavjud"

# Masala(3): Indeks yordamida 3-o'lchamli massivdan elementlarni kesib olish
Masala : 3-o'lchamli massivni quyidagi listdan yarating, hamda 12, 13, 15, va 16 elementlarini kesib oluvchi funksiyani davom ettiring.

In [44]:
# JAVOBNI SHU YERGA YOZING
def sliced_array_3d():
    """3-o'lchamli massivni yuqoridagi listdan yaratish,
    hamda 12, 13, 15, va 16 elementlarini kesib olish funksiyasi"""
    arr3d = np.array([[[ 0,  1,  2],
                    [ 3,  4,  5],
                    [ 6,  7,  8]],

                  [[ 9, 10, 11],
                    [12, 13, 14],
                    [15, 16, 17]],

                  [[18, 19, 20],
                    [21, 22, 23],
                    [24, 25, 26]]])
    return arr3d[1][1:, :2]
sliced_array_3d()

array([[12, 13],
       [15, 16]])

In [45]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Funksiyani tekshirish"""
sl_arr_3d = sliced_array_3d() # kesib olingan massiv
assert sl_arr_3d.size == 4, f"kesib olingan elementlar sonida xatolik" # elementlar soni
assert type(sl_arr_3d) == np.ndarray, f"massiv aniqlanmadi" #numpy array
# elementwise test
test_arr = np.array([[12, 13],
                     [15, 16]])
assert sl_arr_3d.shape == (2,2), f"kesib olingan massiv shaklida xatolik mavjud"
assert True in np.in1d(sl_arr_3d, test_arr), f"elemtlararo xatolik mavjud"

# Masala(4): Boolean indeks yordamida 2-o'lchamli massivlardan elementlarni kesib olish
Masala : Bizlarda,
Mana shu ma'lumotlardan Javohir va Elyor ismlariga tegishli ma'lumotlarni Boolean indekslash yordamida kesib olish funksiyasini davom ettiring. Yordam : Boolean indekslash video darsligiga murojat qiling. Natija: Natija (4, 4) o'lchamli massiv ko'rinishida, hamda dastlabki ikkita qattori quyidagicha

In [50]:
# JAVOBNI SHU YERGA YOZING
def boolean_slicing():
    """Boolean indekslash yordamida ma'lumotlarni kesib olish """
    names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
    data = np.array([[5, 6, 1, 1],
                     [9, 1, 1, 1],
                     [7, 7, 4, 2],
                     [1, 5, 1, 9],
                     [9, 9, 4, 5],
                     [7, 5, 9, 6],
                     [5, 3, 7, 4]])
    mask = (names == 'Javohir') | (names == 'Elyor')
    return data[mask]
boolean_slicing()

array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])

In [60]:
#@title Tekshirish (natijada hech qanday xatolik yuz bermasligi kerak)
"""Funksiyani tekshirish"""
bool_idx = boolean_slicing() # kesib olingan massiv
assert bool_idx.size == 16, f"kesib olingan elementlar sonida xatolik mavjud"  # elementlar soni
assert type(bool_idx) == np.ndarray, f"massiv aniqlanmadi" #numpy array
print(type(bool_idx) == np.ndarray)
# elementwise test
test_arr = np.array([[7, 7, 4, 2],
                     [1, 5, 1, 9],
                     [7, 5, 9, 6],
                     [5, 3, 7, 4]])
assert bool_idx.shape == (4,4), f"kesib olingan massiv shaklida xatolik mavjud"
print(bool_idx.shape == (4,4))
assert True in np.in1d(bool_idx, test_arr), f"elemetlararo xatolik mavjud"
print(True in np.in1d(bool_idx, test_arr))

True
True
True
