<a href="https://colab.research.google.com/github/eraliabd/DataScience/blob/main/%237_Logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ma'lumotlar tahlili. (NumPy kutubxonasi)**

# **NumPy kutubxonasi bilan ishlash**

 NumPy kutubxonasini chaqirib olish.

In [1]:
import numpy as np

# Massivga yo'naltirilgan dasturlash

**Mantiqiy shart operatorlarni massiv operator sifatida qo'llash**

Shart operatori sifatida `where` dan foydalanish

Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: `xarr` va yarr. Agarda shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan aksincha esa `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [2]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [3]:
# Shart
cond = np.array([True, False, True, True, False])

In [4]:
# where
result = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [5]:
arr = np.random.randn(4, 4)  # (4, 4) taxminiy massiv
arr

array([[ 8.07324317e-01,  2.28093671e+00,  8.78112067e-01,
        -6.77284250e-01],
       [ 7.45626691e-02, -2.80301589e-01, -3.70315666e-01,
         2.63031221e-01],
       [-5.30576906e-01, -8.74640051e-02,  2.51486805e+00,
         5.37461398e-01],
       [ 3.13612028e-03, -3.21082409e+00, -5.48951236e-02,
         2.77160662e-01]])

In [6]:
# where
results = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarin esa 2 ga almashitirish
results

array([[ 2,  2,  2, -2],
       [ 2, -2, -2,  2],
       [-2, -2,  2,  2],
       [ 2, -2, -2,  2]])