<a href="https://colab.research.google.com/github/eraliabd/DataScience/blob/main/%238_Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ma'lumotlar tahlili. (NumPy kutubxonasi)**

# **NumPy kutubxonasi bilan ishlash**

 NumPy kutubxonasini chaqirib olish.

In [3]:
import numpy as np

# Massivga yo'naltirilgan dasturlash

### Arifmetik amallar

### Ko'paytirish, bo'lish, qo'shish, ayirish va h.k amallar

In [4]:
# data
arr1 = np.arange(6).reshape(2, 3) # 0~6 gach bo'lgan elementlardan tashkil topgan array
arr2 = np.arange(6, 12).reshape(2, 3) # 6 dan 11 gacha bo'lgan elementlardan tashkil topgan array

In [5]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
# Ko'paytirish
arr1 * arr2 # arr1 ning elementlarini arr2 ning mos elementlariga ko'paytirib beradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [8]:
# bo'lish
arr2/arr1 # arr1 ning elementlarini arr2 ning mos elementlariga bo'lib beradi

<ipython-input-8-b0ffd924afb6>:2: RuntimeWarning: divide by zero encountered in divide
  arr2/arr1 # arr1 ning elementlarini arr2 ning mos elementlariga bo'lib beradi


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [9]:
arr1/arr2

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [10]:
# qo'shish
arr1 + arr2 # arr1 ning elementlarini arr2 ning mos elementlariga qo'shib beradi

array([[ 6,  8, 10],
       [12, 14, 16]])

In [11]:
# ayirish
arr2 - arr1 # arr2 ning elementlaridan arr1 mos elementlarini ayirish

array([[6, 6, 6],
       [6, 6, 6]])

In [12]:
# kvadratga oshirish (square)
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [13]:
# kvadrat ildizdan (sqrt)
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])